// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data;

namespace ToDoApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211024230921_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApp.Core.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Daily");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Name = "Learn SQL",
                            Period = "Monthly"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2021, 11, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Name = "Learn MVC",
                            Period = "Monthly"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Name = "Write Data Layer",
                            Period = "Weekly"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2021, 10, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Name = "Develop the ToDoApp",
                            Period = "Weekly"
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Name = "Check the MailBox",
                            Period = "Daily"
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2021, 10, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Name = "Something",
                            Period = "Daily"
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2021, 10, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Name = "BlaBla",
                            Period = "Weekly"
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2021, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Name = "EtcEtc",
                            Period = "Monthly"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
