// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data;

namespace ToDoApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211024154352_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApp.Core.Models.ToDoList", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToDoId");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ToDoId = 1,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Period = "Monthly",
                            ToDoName = "Learn SQL"
                        },
                        new
                        {
                            ToDoId = 2,
                            DateTime = new DateTime(2021, 11, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Period = "Monthly",
                            ToDoName = "Learn MVC"
                        },
                        new
                        {
                            ToDoId = 3,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Period = "Weekly",
                            ToDoName = "Write Data Layer"
                        },
                        new
                        {
                            ToDoId = 4,
                            DateTime = new DateTime(2021, 10, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Period = "Weekly",
                            ToDoName = "Develop the ToDoApp"
                        },
                        new
                        {
                            ToDoId = 5,
                            DateTime = new DateTime(2021, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Period = "Daily",
                            ToDoName = "Check the MailBox"
                        },
                        new
                        {
                            ToDoId = 6,
                            DateTime = new DateTime(2021, 10, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Period = "Daily",
                            ToDoName = "Something"
                        },
                        new
                        {
                            ToDoId = 7,
                            DateTime = new DateTime(2021, 10, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            Period = "Weekly",
                            ToDoName = "BlaBla"
                        },
                        new
                        {
                            ToDoId = 8,
                            DateTime = new DateTime(2021, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            Period = "Monthly",
                            ToDoName = "EtcEtc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
